# yamllint disable rule:line-length
---
name: Lite Optimize Strategy RSI

on:
  push:
    branches:
      - 'optimize-lite-strategy-rsi*'
    paths-ignore:
      - '*.json'
      - '*.md'
      - '*.txt'
      - '.git*'
      - '.yamllint'
      - 'LICENSE'

jobs:
  Period:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          # path: /opt
      - name: Optimize RSI1 Period
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          OptOptimize: true
          OptVerbose: true
          OptFormatBrief: true
          OptFormatJson: true
          BtDays: "1-14"
          BtMonths: 1
          BtYears: 2018
          BtSpread: 10
          RunOnStart: "ls -la && id && stat /github/home"
          RunOnSet: 'set_opt_params RSI_Period_M1 $(get_max 2 $(bc <<< "$(input_get RSI_Period_M1) - 2 * 4")) $(bc <<< "$(input_get RSI_Period_M1) + 2 * 4") 2'
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
          RunOnSuccess: 'git diff'
          SetFile: '${{ github.workspace }}/docker/optimization/lite/Strategies/RSI/Indicator/sets/EURUSD/EA31337-RSI_Period_M1.set'
          SetParams: 'RSI_Period_M1'
          TestLimitOpts: "maxdrawdown_enable=1,maxdrawdown=80"
          TestPeriod: 'M30'
          TestReportName: 'EA31337-RSI_Period_M1'
      - name: Optimize RSI5 Period
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          OptOptimize: true
          OptVerbose: true
          OptFormatBrief: true
          OptFormatJson: true
          BtDays: "1-14"
          BtMonths: 1
          BtYears: 2018
          BtSpread: 10
          RunOnSet: 'set_opt_params RSI_Period_M5 $(get_max 2 $(bc <<< "$(input_get RSI_Period_M5) - 2 * 4")) $(bc <<< "$(input_get RSI_Period_M5) + 2 * 4") 2'
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
          RunOnSuccess: 'git diff'
          SetFile: '${{ github.workspace }}/docker/optimization/lite/Strategies/RSI/Indicator/sets/EURUSD/EA31337-RSI_Period_M5.set'
          SetParams: 'RSI_Period_M5'
          TestLimitOpts: "maxdrawdown_enable=1,maxdrawdown=80"
          TestPeriod: 'M30'
          TestReportName: 'EA31337-RSI_Period_M5'
      - name: Optimize RSI15 Period
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          OptOptimize: true
          OptVerbose: true
          OptFormatBrief: true
          OptFormatJson: true
          BtDays: "1-14"
          BtMonths: 1
          BtYears: 2018
          BtSpread: 10
          RunOnSet: 'set_opt_params RSI_Period_M15 $(get_max 2 $(bc <<< "$(input_get RSI_Period_M15) - 2 * 4")) $(bc <<< "$(input_get RSI_Period_M15) + 2 * 4") 2'
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
          RunOnSuccess: 'git diff'
          SetFile: '${{ github.workspace }}/docker/optimization/lite/Strategies/RSI/Indicator/sets/EURUSD/EA31337-RSI_Period_M15.set'
          SetParams: 'RSI_Period_M15'
          TestLimitOpts: "maxdrawdown_enable=1,maxdrawdown=80"
          TestPeriod: 'M30'
          TestReportName: 'EA31337-RSI_Period_M15'
      - name: Optimize RSI30 Period
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          OptOptimize: true
          OptVerbose: true
          OptFormatBrief: true
          OptFormatJson: true
          BtDays: "1-14"
          BtMonths: 1
          BtYears: 2018
          BtSpread: 10
          RunOnSet: 'set_opt_params RSI_Period_M30 $(get_max 2 $(bc <<< "$(input_get RSI_Period_M30) - 2 * 4")) $(bc <<< "$(input_get RSI_Period_M30) + 2 * 4") 2'
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
          RunOnSuccess: 'git diff'
          SetFile: '${{ github.workspace }}/docker/optimization/lite/Strategies/RSI/Indicator/sets/EURUSD/EA31337-RSI_Period_M30.set'
          SetParams: 'RSI_Period_M30'
          TestLimitOpts: "maxdrawdown_enable=1,maxdrawdown=80"
          TestPeriod: 'M30'
          TestReportName: 'EA31337-RSI_Period_M30'
  SignalMethod:
    runs-on: ubuntu-latest
    needs: Period
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Optimize RSI1 SignalMethod
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          OptOptimize: true
          OptVerbose: true
          OptFormatBrief: true
          OptFormatJson: true
          BtDays: "1-5"
          BtMonths: 1
          BtYears: 2018
          BtSpread: 10
          RunOnError: 'show_logs'
          RunOnWarning: 'show_logs'
          RunOnSet: "set_opt_params RSI1_SignalMethod -63 63"
          RunOnSuccess: 'git diff'
          SetFile: '${{ github.workspace }}/docker/optimization/lite/Strategies/RSI/SignalMethod/sets/EURUSD/EA31337-RSI1_SignalMethod.set'
          SetParams: 'RSI1_SignalMethod'
          TestPeriod: "M30"
      - name: Optimize RSI5 SignalMethod
        uses: fx31337/mql-tester-action@master
        with:
          TestExpert: EA31337
          OptOptimize: true
          OptVerbose: true
          OptFormatBrief: true
          OptFormatJson: true
          BtDays: "1-5"
          BtMonths: 1
          BtYears: 2018
          BtSpread: 10
          RunOnError: 'show_logs'
          RunOnSet: "set_opt_params RSI5_SignalMethod -63 63"
          RunOnWarning: 'show_logs && parse_results $@ && exit 0'
          RunOnSuccess: 'git diff'
          SetFile: '${{ github.workspace }}/docker/optimization/lite/Strategies/RSI/SignalMethod/sets/EURUSD/EA31337-RSI5_SignalMethod.set'
          SetParams: 'RSI5_SignalMethod'
          TestPeriod: "M30"
